easycook/config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :ingredients

  get 'tags/:tag', to: 'ingredients#index', as: :tag
  get 'tags', to: 'ingredients#tags'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

easycook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

easycook/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # Associate recipes and ingredients
  has_and_belongs_to_many :recipes

  acts_as_taggable

  def self.search(search)
    if search
      self.where("name like ?", "%#{search}%")
    else
      self.all
    end
  end

end

easycook/app/models/recipe.rb
class Recipe < ApplicationRecord
  # Associate recipes and ingredients
  has_and_belongs_to_many :ingredients

  validates_presence_of :name

    def ingredient_name
      ingredients.try(:name)
    end

    def category_name=(name)
      self.ingredients = Category.find_by_or_create_name(name) if name.present?
    end

    def self.search(search)
      if search
        self.where("name like ?", "%#{search}%")
      else
        self.all
      end
    end
end

easycook/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image
    end
  end
end   

easycook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

easycook/app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
    redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

easycook/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

easycook/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    if params[:tag]
      @ingredients = Ingredient.tagged_with(params[:tag])
    else
      @ingredients = Ingredient.search(params[:search])
    end
  end

  def tags
    @tags = Recipe.tag_counts
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description, :tag_list)
    end
end

easycook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.search(params[:search])
    @ingredients = Ingredient.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @ingredients = Ingredient.all
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @ingredients = Ingredient.all
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :preparing, {ingredient_ids: []})
    end
end

easycook/app/helpers/application_helper.rb
module ApplicationHelper
end

easycook/app/helpers/callbacks_helper.rb
module CallbacksHelper
end

easycook/app/helpers/home_helper.rb
module HomeHelper
end

easycook/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

easycook/app/helpers/recipes_helper.rb
module RecipesHelper
end

easycook/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <!-- Header -->
    <header>
        <div id="home-index">
          <div class="intro-text">
              <div class="intro-lead-in">Seja um Chef você também!</div>
              <div class="intro-heading">EasyCook</div>


              <button type="submit" class="btn btn-xl"><img src = "assets/logo-search.png" > Pesquisar Receitas</button>
          </div>
      </div>
    </header>

    <!-- jQuery -->
    <script src="app/assets/javascripts/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="app/assets/javascripts/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" integrity="sha384-mE6eXfrb8jxl0rzJDBRanYqgBxtJ6Unn4/1F7q4xRRyIw7Vdg9jP4ycT7x1iVsgb" crossorigin="anonymous"></script>

    <!-- Contact Form JavaScript -->
    <script src="app/assets/javascripts/jqBootstrapValidation.js"></script>
    <script src="app/assets/javascripts/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="app/assets/javascripts/agency.min.js"></script>

</body>

</html>

easycook/app/views/ingredients/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">Ingrediente</h2>
            <h3 class="section-subheading text-muted"></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">

<%= form_for(ingredient) do |f| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
          <%= f.label :nome %><br/>
          <%= f.text_field :name, class: "form-control", placeholder: "Coloque aqui o nome do ingrediente *"%>
      </div>

  
  <div class="form-group">
    <%= f.label :tag_list, "Tags (Separadas por Ponto)" %><br>
    <%= f.text_field :tag_list, class:"form-control", placeholder: "Tags separadas por ponto" %>
  </div>

<div class="col-lg-12 text-center">
  <div class="actions">
      <% if ingredient.name != nil%>
          <%= f.submit "Atualizar", class:"btn btn-xl"%>
      <% else %>
          <%= f.submit "Criar", class:"btn btn-xl"%>
      <% end %>
  </div>
<% end %>

easycook/app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Mostrar', @ingredient , class:"btn btn-xl"%>
<%= link_to 'Voltar', ingredients_path , class:"btn btn-xl"%>

easycook/app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<br>
  <div class="row">
      <div class="col-lg-12 text-center">
          <h2 class="section-heading">Ingredientes</h2>
      </div>
  </div>

<%= form_tag ingredients_path, :method => 'get' do %>
  <p>
    <div>
    <div class="col-xs-4 col-xs-offset-4 text-center">
      <div id="search-ingredients">
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag "Procurar", :name => nil, class:"btn btn-xl"%>
    </div>
  </p>
<% end %>

<%= link_to 'Novo Ingrediente', new_ingredient_path , class:"btn btn-xl"%>

<br>
<br>

	<div class="row">
        <div class="span12">
    		<table class="table table-condensed table-hover">
    			<thead>
    				<tr>
    					<th> Nome </th>
    					<th><%=  link_to 'Tags', tags_path %> </th>
    				</tr>
    			</thead>
    			<tbody>
            <% @ingredients.each do |ingredient| %>
    				<tr>
              <td><%= ingredient.name %></td>
              <td><%= raw ingredient.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></td>
              <td><%= link_to image_tag("eye.png", width:24, height:24, border: 0, alt:"Visualizar", title:"Visualizar"), ingredient_path(ingredient) %></td>
              <td><%= link_to image_tag("settings.png", width:24, height:24, border: 0, alt:"Editar", title:"Editar"), edit_ingredient_path(ingredient) %></td>
              <td><%= link_to image_tag("delete-button.png", width:24, height:24, border: 0, alt:"Deletar", title:"Deletar"),
                                        ingredient, method: :delete, data:
                                        { confirm: 'Você tem certeza que quer deletar esse Ingrediente?' } %></td>
    				</tr>
            <% end %>
    			</tbody>
    		</table>
    	</div>
	</div>

easycook/app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Voltar', ingredients_path , class:"btn btn-xl"%>

easycook/app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-lg-12 text-center">
      <div class="intro-text">
          <div class="intro-lead-in", id="ingredients-index">Huuum Chef, temos um delicioso "<%= @ingredient.name %>" aqui!</div>
    </div>
</div>

<div>
  <p>
    <div class="intro-lead-in", id="ingredients-index">Ingrediente:</div>
    <div class="intro-lead-in", id="ingredients-atributes"><%= @ingredient.name %></div>
  </p>

  <p>
    <div class="intro-lead-in", id="ingredients-index">Tags:</div>
    <div class="intro-lead-in", id="ingredients-atributes"><%= @ingredient.tag_list %></div>
   </p>
</div>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) , class:"btn btn-xl"%>
<%= link_to 'Back', ingredients_path, class:"btn btn-xl"%>

easycook/app/views/ingredients/tags.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>
<div id="tag_cloud">
  <% tag_cloud Ingredient.tag_counts, %w[s m l] do |tag, css_class|%>
    <%= link_to tag.name, tag_path(tag.name, class: css_class)%></br>
  <% end %>
</div>

easycook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Easycook</title>

        <!-- Bootstrap Core CSS -->
        <link href="app/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="app/assets/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

        <!-- Theme CSS -->
        <link href="app/assets/stylesheets/agency.min.css" rel="stylesheet">


</head>

    <body id="page-top" class="index">

        <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                    </button>
                    <%= link_to "Easycook", root_path, class:"navbar-brand page-scroll"%>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                      <% if user_signed_in? %>
                            <li>
                                <a class="page-scroll" href="/recipes">Receitas</a>
                            </li>
                            <li>
                                <a class="page-scroll" href="/ingredients">Ingredientes</a>
                            </li>
                            <li><%= link_to "Profile", edit_user_registration_path %></li>
                            <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>

                      <% else %>
                        <li><%= link_to "Sign in", new_user_session_path %></li>
                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                      <% end %>

                    </ul>
                </div>

            </div>

        </nav>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= yield %>

</html>

easycook/app/views/recipes/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">Receita</h2>
            <h3 class="section-subheading text-muted"></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">


  <%= form_for(recipe) do |f| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
          <%= f.label :nome %><br/>
          <%= f.text_field :name, class: "form-control", placeholder: "Coloque aqui o nome da Receita *"%>
      </div>

      <div class="form-group">
        <%= f.label :descrição %><br>
        <%= f.text_area :description, class:"form-control", placeholder: "Descrição do Prato" %>
      </div>

      <div class="field">
        <%= f.collection_check_boxes(:ingredient_ids, @ingredients, :id, :name, checked: recipe.ingredients.map(&:id)) do |b| %>
          <%= b.check_box %> <%= b.label %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :modo_preparo %><br>
        <%= f.text_area :preparing, class:"form-control", placeholder: "Modo de Preparo" %>
      </div>

<div class="col-lg-12 text-center">
  <div class="actions">
      <% if recipe.name != nil%>
          <%= f.submit "Atualizar", class:"btn btn-xl"%>
      <% else %>
          <%= f.submit "Criar", class:"btn btn-xl"%>
      <% end %>
  </div>
<% end %>

easycook/app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Mostrar', @recipe , class:"btn btn-xl" %>
<%= link_to 'Voltar', recipes_path, class:"btn btn-xl" %>

easycook/app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<br>
  <div class="row">
      <div class="col-lg-12 text-center">
          <h2 class="section-heading">Receitas</h2>
      </div>
  </div>

<%= form_tag recipes_path, :method => 'get' do %>
  <p>
    <div>
    <div class="col-xs-4 col-xs-offset-4 text-center">
      <div id="search-ingredients">
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag "Procurar", :name => nil, class:"btn btn-xl"%>
    </div>
  </p>
<% end %>

<%= link_to 'Nova Receita', new_recipe_path , class:"btn btn-xl"%>

<br>
<br>

	<div class="row">
        <div class="span12">
    		<table class="table table-condensed table-hover">
    			<thead>
    				<tr>
              <th>Name</th>
              <th>Description</th>
              <th>Ingredients</th>
              <th>Preparing</th>
              <th colspan="3"></th>
    				</tr>
    			</thead>
    			<tbody>
            <% @recipes.each do |recipe| %>
              <tr>
                <td><%= recipe.name %></td>
                <td><%= recipe.description %></td>
                <td>
                  <% recipe.ingredients.each do |ingredient| %>
                    <%= ingredient.name %><br>
                  <% end %>
                </td>
                <td><%= recipe.preparing %></td>
              <td><%= link_to image_tag("eye.png", width:24, height:24, border: 0, alt:"Visualizar", title:"Visualizar"), recipe_path(recipe) %></td>
              <td><%= link_to image_tag("settings.png", width:24, height:24, border: 0, alt:"Editar", title:"Editar"), edit_recipe_path(recipe) %></td>
              <td><%= link_to image_tag("delete-button.png", width:24, height:24, border: 0, alt:"Deletar", title:"Deletar"),
                                        recipe, method: :delete, data:
                                        { confirm: 'Você tem certeza que quer deletar essa Receita?' } %></td>
    				</tr>
            <% end %>
    			</tbody>
    		</table>
    	</div>
	</div>

easycook/app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Voltar', recipes_path , class:"btn btn-xl" %>

easycook/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-lg-12 text-center">
      <div class="intro-text">
          <div class="intro-lead-in", id="ingredients-index">Huuum Chef, temos um(a) delicioso(a) "<%= @recipe.name %>" aqui!</div>
    </div>
</div>

<div>
  <p>
    <div class="intro-lead-in", id="ingredients-index">Receita:</div>
    <div class="intro-lead-in", id="ingredients-atributes"><%= @recipe.name %></div>
  </p>

  <p>
    <div class="intro-lead-in", id="ingredients-index">Descrição:</div>
    <div class="intro-lead-in", id="ingredients-atributes"><%= @recipe.description %></div>
  </p>

  <p>
    <div class="intro-lead-in", id="ingredients-index">Ingredientes:</div>
    <div class="intro-lead-in", id="ingredients-atributes"><%= @recipe.ingredients.map(&:name).join(',') %></div>
   </p>

   <p>
     <div class="intro-lead-in", id="ingredients-index">Modo de Preparo:</div>
     <div class="intro-lead-in", id="ingredients-atributes"><%= @recipe.preparing %></div>
    </p>

</div>

<%= link_to 'Editar', edit_recipe_path(@recipe) , class:"btn btn-xl"%>
<%= link_to 'Voltar', recipes_path , class:"btn btn-xl"%>